import React, { useState } from 'react';
import { 
  Microscope, 
  Eye, 
  BrainCircuit, 
  HelpCircle, 
  ShieldCheck, 
  AlertOctagon, 
  FileText, 
  CheckCircle2, 
  Sparkles,
  Lock,
  Terminal,
  ShieldAlert
} from 'lucide-react';
import { executeContainment } from '../api/client';

export default function ForensicInspectorPage({ alerts = [], containedEntities = [], onIsolateTarget }) {
  const [selectedAlertId, setSelectedAlertId] = useState(
    alerts[0]?.alert_id || 'ALT-1726132400'
  );
  const [activeTab, setActiveTab] = useState('observed');

  const activeAlert = alerts.find(a => a.alert_id === selectedAlertId) || alerts[0] || {
    alert_id: 'ALT-1726132400',
    attack: 'Rapid Credential Stuffing Burst',
    severity: 'HIGH',
    risk_score: 85,
    server: 'AUTH-01',
    user: 'alice',
    source_ip: '192.168.1.50',
    reason: 'Multiple failed login attempts followed by successful login',
    ai_analysis: {
      confidence: 94,
      mitre_tactic: 'Credential Access',
      mitre_technique: 'Credential Stuffing',
      mitre_code: 'T1110.001',
      summary: 'High-density automated login attempts detected against AUTH-01 endpoint.',
      observed_facts: [
        '12 failed authentication attempts in 4.2 seconds',
        'Single source IP 192.168.1.50 targeting account "alice"',
        'Successful session token issued at 14:10:03'
      ],
      inferred_context: [
        'Adversary utilizing credential database leak',
        'High probability of compromised user credentials',
        'Intent to establish persistence on authentication domain'
      ],
      remediation_steps: [
        'Enforce immediate password reset for user "alice"',
        'Isolate source IP 192.168.1.50 via perimeter firewall',
        'Enable mandatory multi-factor authentication (MFA)'
      ],
      unknowns: [
        'Whether secondary internal tokens were harvested',
        'Exfiltration payload volume prior to detection'
      ]
    }
  };

  const ai = activeAlert?.ai_analysis || {
    observed_facts: [
      `12 failed authentication attempts recorded for user "${activeAlert?.user || 'alice'}"`,
      `Source IP address verified at ${activeAlert?.source_ip || '192.168.1.50'}`,
      `Target host asset identified as ${activeAlert?.server || 'AUTH-01'}`
    ],
    inferred_context: [
      `MITRE ATT&CK Code: T1110 (Credential Access / Brute Force)`,
      `Adversary intent: Account takeover and privilege boundary probing`,
      `High confidence score (94%) generated by Gemini AI Threat Synthesizer`
    ],
    remediation_steps: [
      `Isolate host ${activeAlert?.server || 'AUTH-01'} and source IP ${activeAlert?.source_ip || '192.168.1.50'}`,
      `Invalidate session tokens for user "${activeAlert?.user || 'alice'}"`,
      `Enforce hardware security key multi-factor authentication`
    ],
    unknowns: [
      `Potential lateral movement via cached SSH keys`,
      `Underlying kernel memory trace persistence`
    ]
  };

  const isContained = containedEntities.some(
    e => activeAlert && (e.includes(activeAlert.source_ip) || e.includes(activeAlert.user))
  );

  const handleContain = async () => {
    if (onIsolateTarget && activeAlert) {
      await onIsolateTarget('ip', activeAlert.source_ip);
    } else if (activeAlert) {
      await executeContainment('ip', activeAlert.source_ip, 'isolate');
    }
  };

  return (
    <div className="space-y-6 animate-fadeIn">
      
      {/* Top Banner Header */}
      <div className="bg-zinc-900/90 border border-zinc-800 rounded-xl p-5 backdrop-blur shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-amber-500/10 border border-amber-500/30 text-amber-400">
              <Microscope className="w-6 h-6 text-amber-400" />
            </div>
            <div>
              <h1 className="text-xl font-black text-white uppercase tracking-wider font-sans">
                AEGIS-X
              </h1>
              <p className="text-xs text-zinc-400 font-mono mt-0.5">
                FORENSIC INSPECTOR & LOOPHOLE DOSSIER MATRIX
              </p>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2 font-mono text-xs px-3 py-1.5 rounded-lg bg-amber-500/10 border border-amber-500/30 text-amber-400">
          <Sparkles className="w-4 h-4 text-amber-400" />
          <span>DOSSIER AUDITOR: ACTIVE</span>
        </div>
      </div>

      {/* Main Grid: Alert Selector (Left) & Evidence Tabs (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Col: Incident / Alert Selector (4 Cols) */}
        <div className="lg:col-span-4 space-y-3">
          <h2 className="text-xs font-bold text-amber-400 uppercase tracking-wider font-mono flex items-center gap-2">
            <FileText className="w-4 h-4 text-amber-400" />
            INGESTED AUDIT DOSSIERS
          </h2>

          <div className="space-y-2 max-h-[540px] overflow-y-auto pr-1">
            {alerts.length === 0 ? (
              <div className="bg-zinc-900 border border-zinc-800 p-6 text-center text-zinc-500 font-mono text-xs rounded-xl">
                NO ACTIVE DOSSIERS FOUND.
              </div>
            ) : (
              alerts.map((alt) => {
                const isSelected = selectedAlertId === alt.alert_id;
                return (
                  <div
                    key={alt.alert_id || alt.timestamp}
                    onClick={() => setSelectedAlertId(alt.alert_id)}
                    className={`p-3.5 rounded-xl border transition-all cursor-pointer font-mono text-xs space-y-2 ${
                      isSelected
                        ? 'bg-amber-950/40 border-amber-500 text-white ring-1 ring-amber-500/50 shadow-lg'
                        : 'bg-zinc-900/80 border-zinc-800 text-zinc-400 hover:border-zinc-700 hover:bg-zinc-850'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-zinc-200">{alt.alert_id || 'ALT-DOSSIER'}</span>
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        alt.severity === 'CRITICAL' ? 'bg-rose-950 text-rose-300 border border-rose-800/60' : 'bg-amber-950 text-amber-300 border border-amber-800/60'
                      }`}>
                        {alt.severity}
                      </span>
                    </div>

                    <div className="text-white font-bold truncate">
                      {alt.attack}
                    </div>

                    <div className="flex items-center justify-between text-[11px] text-zinc-500">
                      <span>IP: {alt.source_ip}</span>
                      <span>RISK: {alt.risk_score}/100</span>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* Right Col: Structured Evidence Tabs (8 Cols) */}
        <div className="lg:col-span-8 space-y-4">
          
          {/* Active Dossier Header */}
          <div className="bg-zinc-900/90 border border-zinc-800 rounded-xl p-5 backdrop-blur shadow-xl space-y-4">
            
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 border-b border-zinc-800 pb-4">
              <div>
                <div className="flex items-center gap-2 font-mono text-xs text-amber-400 font-bold mb-1">
                  <span>DOSSIER RECORD ID:</span>
                  <span className="text-white bg-zinc-950 px-2 py-0.5 rounded border border-zinc-800">{activeAlert?.alert_id}</span>
                </div>
                <h2 className="text-lg font-bold text-white font-sans">
                  {activeAlert?.attack}
                </h2>
                <p className="text-xs text-zinc-400 font-mono mt-1">
                  {activeAlert?.reason}
                </p>
              </div>

              <div className="flex items-center gap-3">
                {isContained ? (
                  <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-emerald-950 border border-emerald-500 text-emerald-300 font-mono text-xs">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    <span>CONTAINED / ISOLATED</span>
                  </div>
                ) : (
                  <button
                    type="button"
                    onClick={handleContain}
                    className="px-4 py-2 rounded-lg bg-rose-600 hover:bg-rose-500 text-white font-mono text-xs font-bold uppercase tracking-wider flex items-center gap-2 transition-all shadow-lg"
                  >
                    <ShieldAlert className="w-4 h-4" />
                    <span>ISOLATE ENTITY</span>
                  </button>
                )}
              </div>
            </div>

            {/* Evidence Tab Buttons */}
            <div className="grid grid-cols-3 gap-2">
              <button
                type="button"
                onClick={() => setActiveTab('observed')}
                className={`py-3 px-4 rounded-lg font-mono text-xs font-bold flex items-center justify-center gap-2 transition-all border ${
                  activeTab === 'observed'
                    ? 'bg-cyan-950/60 border-cyan-400 text-cyan-300 shadow-md ring-1 ring-cyan-400/40'
                    : 'bg-zinc-950 border-zinc-800 text-zinc-400 hover:text-white hover:border-zinc-700'
                }`}
              >
                <Eye className="w-4 h-4 text-cyan-400" />
                <span>👁️ OBSERVED FACTS</span>
              </button>

              <button
                type="button"
                onClick={() => setActiveTab('inferred')}
                className={`py-3 px-4 rounded-lg font-mono text-xs font-bold flex items-center justify-center gap-2 transition-all border ${
                  activeTab === 'inferred'
                    ? 'bg-amber-950/60 border-amber-400 text-amber-300 shadow-md ring-1 ring-amber-400/40'
                    : 'bg-zinc-950 border-zinc-800 text-zinc-400 hover:text-white hover:border-zinc-700'
                }`}
              >
                <BrainCircuit className="w-4 h-4 text-amber-400" />
                <span>🧠 INFERRED CONTEXT</span>
              </button>

              <button
                type="button"
                onClick={() => setActiveTab('remediation')}
                className={`py-3 px-4 rounded-lg font-mono text-xs font-bold flex items-center justify-center gap-2 transition-all border ${
                  activeTab === 'remediation'
                    ? 'bg-emerald-950/60 border-emerald-400 text-emerald-300 shadow-md ring-1 ring-emerald-400/40'
                    : 'bg-zinc-950 border-zinc-800 text-zinc-400 hover:text-white hover:border-zinc-700'
                }`}
              >
                <HelpCircle className="w-4 h-4 text-emerald-400" />
                <span>❓ UNKNOWNS & FIXES</span>
              </button>
            </div>

            {/* Evidence Tab Content Container */}
            <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-5 min-h-[280px]">
              
              {/* TAB 1: Observed Facts */}
              {activeTab === 'observed' && (
                <div className="space-y-4 animate-fadeIn font-mono text-xs">
                  <div className="flex items-center gap-2 text-cyan-400 font-bold border-b border-zinc-800 pb-2">
                    <Eye className="w-4 h-4" />
                    <span>VERIFIED TELEMETRY INDICATORS & EMPIRICAL EVIDENCE</span>
                  </div>

                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3 bg-zinc-900/60 p-3 rounded-lg border border-zinc-800 text-zinc-300">
                    <div>
                      <span className="text-zinc-500 block text-[10px]">SOURCE IP</span>
                      <span className="font-bold text-white">{activeAlert?.source_ip}</span>
                    </div>
                    <div>
                      <span className="text-zinc-500 block text-[10px]">TARGET USER</span>
                      <span className="font-bold text-white">{activeAlert?.user}</span>
                    </div>
                    <div>
                      <span className="text-zinc-500 block text-[10px]">TARGET HOST</span>
                      <span className="font-bold text-white">{activeAlert?.server}</span>
                    </div>
                    <div>
                      <span className="text-zinc-500 block text-[10px]">RISK SCORE</span>
                      <span className="font-bold text-amber-400">{activeAlert?.risk_score}/100</span>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <span className="text-zinc-400 font-bold block">OBSERVED FACT LOG:</span>
                    <ul className="space-y-2">
                      {(ai.observed_facts || []).map((fact, idx) => (
                        <li key={idx} className="flex items-start gap-2 bg-zinc-900 p-2.5 rounded border border-zinc-800 text-zinc-300">
                          <CheckCircle2 className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
                          <span>{fact}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}

              {/* TAB 2: Inferred Context */}
              {activeTab === 'inferred' && (
                <div className="space-y-4 animate-fadeIn font-mono text-xs">
                  <div className="flex items-center gap-2 text-amber-400 font-bold border-b border-zinc-800 pb-2">
                    <BrainCircuit className="w-4 h-4" />
                    <span>MITRE ATT&CK MAPPING & ADVERSARY INTENT SYNTHESIS</span>
                  </div>

                  <div className="bg-amber-950/20 border border-amber-500/30 p-3.5 rounded-lg text-amber-200">
                    <span className="font-bold text-amber-400 block mb-1">SYNTHESIZED INTENT SUMMARY:</span>
                    <span>{ai.summary || 'High confidence threat assessment based on correlation logs and anomaly scoring.'}</span>
                  </div>

                  <div className="space-y-2">
                    <span className="text-zinc-400 font-bold block">INFERRED ADVERSARY CONTEXT:</span>
                    <ul className="space-y-2">
                      {(ai.inferred_context || []).map((ctx, idx) => (
                        <li key={idx} className="flex items-start gap-2 bg-zinc-900 p-2.5 rounded border border-zinc-800 text-zinc-300">
                          <BrainCircuit className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                          <span>{ctx}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}

              {/* TAB 3: Unknowns & Remediation */}
              {activeTab === 'remediation' && (
                <div className="space-y-4 animate-fadeIn font-mono text-xs">
                  <div className="flex items-center gap-2 text-emerald-400 font-bold border-b border-zinc-800 pb-2">
                    <HelpCircle className="w-4 h-4" />
                    <span>ENGINEERING REMEDIATION & POTENTIAL BLIND SPOTS</span>
                  </div>

                  <div className="space-y-2">
                    <span className="text-emerald-400 font-bold block">RECOMMENDED REMEDIATION ACTIONS:</span>
                    <ul className="space-y-2">
                      {(ai.remediation_steps || []).map((step, idx) => (
                        <li key={idx} className="flex items-start gap-2 bg-emerald-950/30 p-2.5 rounded border border-emerald-800/40 text-emerald-200">
                          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                          <span>{step}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="space-y-2 pt-2">
                    <span className="text-rose-400 font-bold block">IDENTIFIED UNKNOWNS & BLIND SPOTS:</span>
                    <ul className="space-y-2">
                      {(ai.unknowns || []).map((unk, idx) => (
                        <li key={idx} className="flex items-start gap-2 bg-rose-950/30 p-2.5 rounded border border-rose-800/40 text-rose-200">
                          <AlertOctagon className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                          <span>{unk}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}

            </div>

          </div>

        </div>

      </div>

    </div>
  );
}
