import React from 'react';
import { Trash2 } from 'lucide-react';
import { soundFx } from '../utils/audio';

export default function AlertsPage({ alerts = [], onPurgeAlerts }) {
  return (
    <div className="space-y-6 font-sans">
      <div className="p-4 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-between font-mono-code text-xs">
        <div>
          <h2 className="text-sm font-extrabold text-slate-100 uppercase tracking-wider">
            SECURITY ALERTS ROSTER
          </h2>
          <p className="text-slate-400 text-[11px] mt-0.5">
            Real-time security alerts generated by the AEGIS-X Decision Engine.
          </p>
        </div>

        <button
          onClick={() => {
            soundFx.playPurgeSweep();
            if (onPurgeAlerts) onPurgeAlerts();
          }}
          className="px-3 py-1.5 rounded bg-rose-950 border border-rose-500/40 text-rose-300 font-bold flex items-center gap-1.5"
        >
          <Trash2 className="w-3.5 h-3.5" /> Purge Alerts
        </button>
      </div>

      <div className="space-y-3 font-mono-code text-xs">
        {alerts.length === 0 ? (
          <div className="p-8 rounded-lg bg-slate-900 border border-slate-800 text-center text-slate-500">
            NO ACTIVE ALERTS IN QUEUE.
          </div>
        ) : (
          alerts.map((alert, idx) => (
            <div
              key={alert.alert_id || idx}
              className={`p-4 rounded-lg border ${
                alert.severity === 'CRITICAL'
                  ? 'bg-rose-950/40 border-rose-500/50'
                  : 'bg-slate-900/90 border-slate-800'
              }`}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                      alert.severity === 'CRITICAL' ? 'bg-rose-950 text-rose-400 border border-rose-500/40' : 'bg-amber-950 text-amber-400 border border-amber-500/40'
                    }`}>
                      {alert.severity}
                    </span>
                    <span className="font-bold text-slate-100 text-sm font-sans">{alert.attack}</span>
                    <span className="text-slate-500 text-[11px]">{alert.alert_id}</span>
                  </div>
                  <p className="text-slate-300 text-xs font-sans">{alert.reason}</p>
                </div>

                <div className="flex items-center gap-4 text-xs text-slate-400">
                  <span>Server: <strong className="text-slate-200">{alert.server}</strong></span>
                  <span>User: <strong className="text-cyan-400">{alert.user}</strong></span>
                  <span>IP: <strong className="text-slate-200">{alert.source_ip}</strong></span>
                  <span className="px-2.5 py-1 rounded bg-slate-950 text-amber-400 font-bold border border-slate-800">
                    Risk: {alert.risk_score}
                  </span>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
